spring:
  application:
    name: BlogsEnd
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # ??? blog_db ???????????
    url: jdbc:mysql://localhost:3306/blog_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password:  # <-- ???????

server:
  port: 8081 # ?????????

mybatis:
  mapper-locations: classpath:mapper/*.xml # ?? MyBatis ????? SQL ????
  configuration:
    map-underscore-to-camel-case: true # ?????????? (????? create_time ????? Java ?? createTime)